name: pullrequest

on:
  pull_request:
    branches:
      - master

env:
  APP_IMAGE_NAME: hexletbasics/services-app
  BUILDKIT_INLINE_CACHE: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/checkout@v2

      - name: Build App
        uses: docker/build-push-action@v2
        with:
          context: services/app
          file: services/app/Dockerfile.production
          cache-from: type=registry,ref=${{ env.APP_IMAGE_NAME }}:cached
          tags: |
            ${{ env.APP_IMAGE_NAME }}:cached
            ${{ env.APP_IMAGE_NAME }}:latest

      - name: Check
        run: |
          docker-compose --file docker-compose.yml up --abort-on-container-exit
